# Generated by Django 5.2 on 2025-05-15 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0002_ingridient_dish_description_dish_image_dish_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Ingredient Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Ingredient",
                "verbose_name_plural": "Ingredients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Recommendation Tag Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=110, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Recommendation Tag",
                "verbose_name_plural": "Recommendation Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StandardCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Standard Category Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=110, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Sort Order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Category",
                "verbose_name_plural": "Standard Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": [
                    "standard_category__order",
                    "standard_category__name",
                    "name",
                ],
                "verbose_name": "Dish",
                "verbose_name_plural": "Dishes",
            },
        ),
        migrations.AlterModelOptions(
            name="ingrtodish",
            options={
                "verbose_name": "Ingredient in Dish",
                "verbose_name_plural": "Ingredients in Dishes",
            },
        ),
        migrations.AddField(
            model_name="dish",
            name="is_spicy",
            field=models.BooleanField(default=False, verbose_name="Spicy"),
        ),
        migrations.AddField(
            model_name="dish",
            name="is_vegetarian",
            field=models.BooleanField(default=False, verbose_name="Vegetarian"),
        ),
        migrations.AddField(
            model_name="ingrtodish",
            name="unit",
            field=models.CharField(default="g", max_length=20, verbose_name="Unit"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="dish_images/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Dish Name"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="ingrtodish",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dishes.dish",
                verbose_name="Dish",
            ),
        ),
        migrations.AlterField(
            model_name="ingrtodish",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Quantity"
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="ingredients_list",
            field=models.ManyToManyField(
                blank=True,
                through="dishes.IngrToDish",
                to="dishes.ingredient",
                verbose_name="Ingredients",
            ),
        ),
        migrations.AlterField(
            model_name="ingrtodish",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dishes.ingredient",
                verbose_name="Ingredient",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ingrtodish",
            unique_together={("dish", "ingredient")},
        ),
        migrations.AddField(
            model_name="dish",
            name="recommendation_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="recommended_dishes",
                to="dishes.recommendationtag",
                verbose_name="Recommendation Tags",
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="standard_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dishes",
                to="dishes.standardcategory",
                verbose_name="Standard Category",
            ),
        ),
        migrations.DeleteModel(
            name="Ingridient",
        ),
    ]
