# Generated by Django 5.1.2 on 2025-04-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='table_number',
        ),
    ]
