# Generated by Django 5.1.2 on 2025-05-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_table', '0003_alter_ordered_table_client_id_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered_table',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
