# Generated by Django 5.1.2 on 2025-05-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_table', '0004_ordered_table_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_table',
            name='date',
        ),
        migrations.AlterField(
            model_name='ordered_table',
            name='Order_time',
            field=models.DateField(),
        ),
    ]
