# Generated by Django 5.1.2 on 2025-05-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_table', '0005_remove_ordered_table_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_available',
        ),
        migrations.AddField(
            model_name='ordered_table',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
