# Generated by Django 5.1.2 on 2025-05-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_table', '0006_remove_table_is_available_ordered_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_table',
            name='name',
        ),
    ]
