name: Testing deployment 

on: 
  [workflow_dispatch]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build and publish container
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}
        tags: latest
        registry: docker.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
  Deploy:
    needs: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Deploy container
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker-compose down
          docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:latest
          docker-compose up -d
